export default {
    ADD_ATTENDANCE: 'ADD_ATTENDANCE',
    ADD_CLASS: 'ADD_CLASS',
    ADD_STUDENT: 'ADD_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
    SAVE_TEACHER_INFO: 'SAVE_TEACHER_INFO',
    EDIT_CURRENT_ASSIGNMENT: 'EDIT_CURRENT_ASSIGNMENT',
    COMPLETE_CURRENT_ASSIGNMENT: 'COMPLETE_CURRENT_ASSIGNMENT',
    SAVE_EVALUATION_PAGE: 'SAVE_EVALUATION_PAGE',
    UPDATE_STUDENT_IMAGE: 'UPDATE_STUDENT_IMAGE',
    SET_FIRST_RUN_COMPLETED: 'SET_FIRST_RUN_COMPLETED'
}
