export default {
    images: [
        require('assets/images/generic-icons/is-icon-0.png'),
        require('assets/images/generic-icons/is-icon-7.png'),
        require('assets/images/generic-icons/is-icon-1.png'),
        require('assets/images/generic-icons/is-icon-2.png'),
        require('assets/images/generic-icons/is-icon-8.png'),
        require('assets/images/generic-icons/is-icon-6.png'),
        require('assets/images/generic-icons/is-icon-12.png'),
        require('assets/images/generic-icons/is-icon-14.png'),
        require('assets/images/teacher-icons/female1.gif'), 
        require('assets/images/teacher-icons/female2.gif'),
        require('assets/images/teacher-icons/female3.gif'), 
        require('assets/images/teacher-icons/female4.gif'), 
        require('assets/images/teacher-icons/female7.gif'), 
        require('assets/images/teacher-icons/female8.gif'), 
        require('assets/images/teacher-icons/female9.gif'),
        require('assets/images/teacher-icons/female10.gif'), 
        require('assets/images/teacher-icons/female11.gif'), 
        require('assets/images/teacher-icons/female12.gif'), 
        require('assets/images/teacher-icons/male1.gif'), 
        require('assets/images/teacher-icons/male2.gif'),
        require('assets/images/teacher-icons/male3.gif'), 
        require('assets/images/teacher-icons/male4.gif'), 
        require('assets/images/teacher-icons/male7.gif'), 
        require('assets/images/teacher-icons/male8.gif'), 
        require('assets/images/teacher-icons/male9.gif'),
        require('assets/images/teacher-icons/male10.gif'), 
        require('assets/images/teacher-icons/male11.gif'), 
        require('assets/images/teacher-icons/male12.gif'), 
    ],
    genderNeutralImages: [0, 1, 2, 3, 4, 5, 6, 7],
    maleImages: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    femaleImages: [18, 19,20, 21, 22, 23, 24, 25, 26, 27]
}